[package]
name = "denise-winit"
description = "Desktop development and preview backend for Denise, on winit + softbuffer."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = "../README.md"
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
denise = { workspace = true, features = ["std"] }
softbuffer = { workspace = true }
thiserror = { workspace = true, features = ["std"] }
winit = { workspace = true }

[dev-dependencies]
denise-render = { workspace = true, features = ["std"] }

[lints.rust]
missing_docs = "warn"

[lints.clippy]
undocumented_unsafe_blocks = "warn"
